-- ---------------------------------------------------------------------------
-- Video meetings with end-to-end encryption.
--
-- Run once against each environment's database (the local container picks this
-- up automatically through schema.sql):
--
--   mysql -h <host> -u <user> -p <database> < infra/mysql/migrations/001_video_meetings.sql
--
-- Nothing here stores meeting media or a usable encryption key: only public
-- keys and ciphertext sealed to those public keys.
-- ---------------------------------------------------------------------------

-- The LiveKit room name is generated by the server when the call first starts,
-- so a meeting id can never be turned into a joinable room name by guessing.
ALTER TABLE meetings
  ADD COLUMN room_name VARCHAR(120) NULL,
  ADD COLUMN e2ee_key_version INT NOT NULL DEFAULT 0;

ALTER TABLE meetings
  ADD CONSTRAINT uniq_meetings_room_name UNIQUE (room_name);

-- The public half of each browser's identity key pair. The private half is a
-- non-extractable key that never leaves the device it was generated on.
CREATE TABLE IF NOT EXISTS e2ee_device_keys (
  user_type   ENUM('student', 'faculty') NOT NULL,
  user_id     VARCHAR(191) NOT NULL,
  public_key  TEXT NOT NULL,
  fingerprint VARCHAR(64) NOT NULL,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_type, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A room key sealed to one recipient's public key. The server relays these
-- blobs but holds no private key, so it cannot open them.
CREATE TABLE IF NOT EXISTS e2ee_key_envelopes (
  envelope_id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meeting_id           INT NOT NULL,
  key_version          INT NOT NULL,
  recipient_type       ENUM('student', 'faculty') NOT NULL,
  recipient_id         VARCHAR(191) NOT NULL,
  recipient_public_key TEXT NOT NULL,
  ephemeral_public_key TEXT NOT NULL,
  salt                 VARCHAR(128) NOT NULL,
  iv                   VARCHAR(64) NOT NULL,
  ciphertext           TEXT NOT NULL,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_envelopes_meeting FOREIGN KEY (meeting_id)
    REFERENCES meetings(meeting_id) ON DELETE CASCADE,
  UNIQUE KEY uniq_envelope (meeting_id, key_version, recipient_type, recipient_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Raised by a participant whose current device holds no envelope yet. Another
-- participant that has the key seals it for them.
CREATE TABLE IF NOT EXISTS e2ee_key_requests (
  request_id        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meeting_id        INT NOT NULL,
  requester_type    ENUM('student', 'faculty') NOT NULL,
  requester_id      VARCHAR(191) NOT NULL,
  device_public_key TEXT NOT NULL,
  fingerprint       VARCHAR(64) NOT NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_key_requests_meeting FOREIGN KEY (meeting_id)
    REFERENCES meetings(meeting_id) ON DELETE CASCADE,
  UNIQUE KEY uniq_key_request (meeting_id, requester_type, requester_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
