-- ---------------------------------------------------------------------------
-- Local development schema.
--
-- Production runs on MySQL hosted at Aiven; this file recreates the same
-- structure in a local container so the app can be developed and tested
-- without the remote database. It is derived from the queries in
-- packages/backend/src/models.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS faculty (
  email          VARCHAR(191) NOT NULL PRIMARY KEY,
  name           VARCHAR(191) NOT NULL,
  designation    VARCHAR(191)  NULL,
  department     VARCHAR(191)  NULL,
  phone_number   VARCHAR(32)   NULL,
  linked_in      VARCHAR(255)  NULL,
  muj_page       VARCHAR(255)  NULL,
  password_hash  VARCHAR(255) NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS student (
  registration_no        VARCHAR(64) NOT NULL PRIMARY KEY,
  name                   VARCHAR(191) NOT NULL,
  degree                 VARCHAR(191) NULL,
  branch                 VARCHAR(191) NULL,
  year                   INT          NULL,
  gender                 VARCHAR(32)  NULL,
  dob                    DATE         NULL,
  linked_in              VARCHAR(255) NULL,
  github                 VARCHAR(255) NULL,
  password_hash          VARCHAR(255) NOT NULL,
  assigned_faculty_email VARCHAR(191) NULL,
  created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_student_faculty FOREIGN KEY (assigned_faculty_email)
    REFERENCES faculty(email) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS queries (
  query_id     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id   VARCHAR(64) NOT NULL,
  category     VARCHAR(191) NOT NULL,
  subcategory  VARCHAR(191) NOT NULL,
  subject      VARCHAR(255) NOT NULL,
  description  TEXT NOT NULL,
  status       ENUM('Pending', 'Resolved') NOT NULL DEFAULT 'Pending',
  response     TEXT NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at TIMESTAMP NULL,
  CONSTRAINT fk_queries_student FOREIGN KEY (student_id)
    REFERENCES student(registration_no) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_queries_student (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meetings (
  meeting_id    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id    VARCHAR(64) NOT NULL,
  faculty_email VARCHAR(191) NOT NULL,
  initiated_by  ENUM('student', 'faculty') NOT NULL,
  reason        TEXT NULL,
  status        ENUM('pending', 'accepted', 'ongoing', 'completed') NOT NULL DEFAULT 'pending',
  student_ready TINYINT(1) NOT NULL DEFAULT 0,
  faculty_ready TINYINT(1) NOT NULL DEFAULT 0,
  marks         INT NULL,
  -- Video call: the room name is generated by the server on first join, and
  -- the key version tracks the current end-to-end encryption generation.
  room_name        VARCHAR(120) NULL UNIQUE,
  e2ee_key_version INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at  TIMESTAMP NULL,
  CONSTRAINT fk_meetings_student FOREIGN KEY (student_id)
    REFERENCES student(registration_no) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_meetings_faculty FOREIGN KEY (faculty_email)
    REFERENCES faculty(email) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_meetings_student (student_id),
  INDEX idx_meetings_faculty (faculty_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meeting_skill_options (
  skill_id   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  skill_name VARCHAR(191) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meeting_skills (
  meeting_id INT NOT NULL,
  skill_id   INT NOT NULL,
  PRIMARY KEY (meeting_id, skill_id),
  CONSTRAINT fk_meeting_skills_meeting FOREIGN KEY (meeting_id)
    REFERENCES meetings(meeting_id) ON DELETE CASCADE,
  CONSTRAINT fk_meeting_skills_option FOREIGN KEY (skill_id)
    REFERENCES meeting_skill_options(skill_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO meeting_skill_options (skill_name) VALUES
  ('Communication'),
  ('Problem Solving'),
  ('Teamwork'),
  ('Technical Depth'),
  ('Time Management'),
  ('Presentation');

-- ---------------------------------------------------------------------------
-- Mentor-shared learning resources (see migrations/002_resources.sql for the
-- equivalent migration to run against an existing database).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS resources (
  resource_id   INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  faculty_email VARCHAR(191) NOT NULL,
  title         VARCHAR(255) NOT NULL,
  description   TEXT NULL,
  url           VARCHAR(1024) NULL,
  category      VARCHAR(191) NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_resources_faculty FOREIGN KEY (faculty_email)
    REFERENCES faculty(email) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_resources_faculty (faculty_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- Direct messages between a student and their mentor (see
-- migrations/003_messages.sql). Stored server-side in plaintext, unlike the
-- in-call chat which rides the meeting's end-to-end encrypted data channel.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS messages (
  message_id    INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id    VARCHAR(64) NOT NULL,
  faculty_email VARCHAR(191) NOT NULL,
  sender_type   ENUM('student', 'faculty') NOT NULL,
  body          TEXT NOT NULL,
  created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at       TIMESTAMP NULL,
  CONSTRAINT fk_messages_student FOREIGN KEY (student_id)
    REFERENCES student(registration_no) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_messages_faculty FOREIGN KEY (faculty_email)
    REFERENCES faculty(email) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_messages_thread (student_id, faculty_email, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- End-to-end encryption key distribution (see migrations/001_video_meetings.sql
-- for the equivalent migration to run against an existing database).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS e2ee_device_keys (
  user_type   ENUM('student', 'faculty') NOT NULL,
  user_id     VARCHAR(191) NOT NULL,
  public_key  TEXT NOT NULL,
  fingerprint VARCHAR(64) NOT NULL,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_type, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS e2ee_key_envelopes (
  envelope_id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meeting_id           INT NOT NULL,
  key_version          INT NOT NULL,
  recipient_type       ENUM('student', 'faculty') NOT NULL,
  recipient_id         VARCHAR(191) NOT NULL,
  recipient_public_key TEXT NOT NULL,
  ephemeral_public_key TEXT NOT NULL,
  salt                 VARCHAR(128) NOT NULL,
  iv                   VARCHAR(64) NOT NULL,
  ciphertext           TEXT NOT NULL,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_envelopes_meeting FOREIGN KEY (meeting_id)
    REFERENCES meetings(meeting_id) ON DELETE CASCADE,
  UNIQUE KEY uniq_envelope (meeting_id, key_version, recipient_type, recipient_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS e2ee_key_requests (
  request_id        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meeting_id        INT NOT NULL,
  requester_type    ENUM('student', 'faculty') NOT NULL,
  requester_id      VARCHAR(191) NOT NULL,
  device_public_key TEXT NOT NULL,
  fingerprint       VARCHAR(64) NOT NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_key_requests_meeting FOREIGN KEY (meeting_id)
    REFERENCES meetings(meeting_id) ON DELETE CASCADE,
  UNIQUE KEY uniq_key_request (meeting_id, requester_type, requester_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
